export const AVAILABLE_CURRENCIES = [
  { code: 'KRW', name: '대한민국 원 (KRW)', symbol: '₩' },
  { code: 'USD', name: '미국 달러 (USD)', symbol: '$' },
  { code: 'JPY', name: '일본 엔 (JPY)', symbol: '¥' },
  { code: 'EUR', name: '유로 (EUR)', symbol: '€' },
  { code: 'GBP', name: '영국 파운드 (GBP)', symbol: '£' },
  { code: 'CNY', name: '중국 위안 (CNY)', symbol: '¥' },
  { code: 'HKD', name: '홍콩 달러 (HKD)', symbol: '$' },
  { code: 'SGD', name: '싱가포르 달러 (SGD)', symbol: '$' },
  { code: 'CAD', name: '캐나다 달러 (CAD)', symbol: '$' },
  { code: 'AUD', name: '호주 달러 (AUD)', symbol: '$' },
  { code: 'NZD', name: '뉴질랜드 달러 (NZD)', symbol: '$' },
  { code: 'CHF', name: '스위스 프랑 (CHF)', symbol: 'Fr' },
  { code: 'SEK', name: '스웨덴 크로나 (SEK)', symbol: 'kr' },
  { code: 'NOK', name: '노르웨이 크로네 (NOK)', symbol: 'kr' },
  { code: 'DKK', name: '덴마크 크로네 (DKK)', symbol: 'kr' },
  { code: 'MXN', name: '멕시코 페소 (MXN)', symbol: '$' },
  { code: 'BRL', name: '브라질 레알 (BRL)', symbol: 'R$' },
  { code: 'INR', name: '인도 루피 (INR)', symbol: '₹' },
  { code: 'IDR', name: '인도네시아 루피아 (IDR)', symbol: 'Rp' },
  { code: 'THB', name: '태국 바트 (THB)', symbol: '฿' },
  { code: 'TRY', name: '터키 리라 (TRY)', symbol: '₺' },
];

export const TREND_CURRENCY_CODES = ['KRW', 'USD', 'JPY', 'CNY', 'EUR', 'GBP'];
